name: Build and analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build and analyze
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '16.1'

      - name: Build and analyze
        run: xcodebuild clean build analyze -scheme EMTodoList CODE_SIGNING_ALLOWED=NO
        working-directory: ./src
